-   id: htmlhint
    name: NodeJS HTML syntax linter (htmlhint)
    entry: htmlhint
    language: node
    files: .*\.(html|hbs)$
    additional_dependencies: ['htmlhint']
-   id: htmllint
    name: NodeJS HTML syntax linter (htmllint)
    entry: htmllint
    language: node
    files: .*\.(html|hbs)$
    additional_dependencies: ['htmllint-cli']
-   id: dockerfile_lint
    name: Dockerfile linter
    entry: dockerfile_lint
    args: [--dockerfile]
    language: node
    additional_dependencies: [dockerfile_lint]
    files: Dockerfile.*
-   id: markdown-toc
    name: Insert a table of contents in Markdown files, like a README.md
    entry: markdown-toc
    args: [-i]
    language: node
    additional_dependencies: [markdown-toc]
    files: .*\.md$
